name: Overwrite Database.js

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite db.js
        uses: "DamianReeves/write-file-action@v1.0"
        with:
          path: src/config/Database.js
          write-mode: overwrite
          contents: |
            const { Sequelize } = require('sequelize');
            const sequelize = new Sequelize(
              process.env.DATABASE_URL,
              {
                dialect: 'postgres',
                dialectOptions: {
                  ssl: { rejectUnauthorized: false }
                },
                logging: true,
                define: {
                  // hooks globais, atingem todos os modelos
                  hooks: {
                    afterCreate: model => {
                      console.log('\x1b[37m\x1b[46m ' + model.constructor.name + '(#' + model.id + ') criado \x1b[0m ')
                    },
                    afterUpdate: model => {
                      console.log('\x1b[37m\x1b[43m ' + model.constructor.name + '(#' + model.id + ') atualizado \x1b[0m ')
                    },
                    afterDestroy: model => {
                      console.log('\x1b[37m\x1b[41m ' + model.constructor.name + '(#' + model.id + ') eliminado ⚠ \x1b[0m ')
                    }
                  }
                }
              }
            )
            sequelize.sync()
            module.exports = sequelize 
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions'
